# -*- coding: utf-8 -*-
"""Coffee Shop Daily Orders Forecasting Using SES (Simple Exponential Smoothing)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUDvJX-MNTUEOLAtxOhx8lJFIdDfLei5

Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.holtwinters import SimpleExpSmoothing

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

"""Load Dataset"""

df = pd.read_csv('/content/raw_orders_coffee.csv')

df.head()

"""Dataset Information"""

print("Shape:", df.shape)

df.info()

"""Convert Date Column"""

df['Date'] = pd.to_datetime(
    df['Date'],
    dayfirst=True
)

"""Create Daily Orders Dataset

SES needs one variable.

Convert order-level data to daily orders.
"""

daily_orders = df.groupby(
    'Date'
).size().reset_index(
    name='Orders'
)

daily_orders.head()

"""Check Total Days"""

print("Total Days :", len(daily_orders))

print("Start Date :", daily_orders['Date'].min())

print("End Date :", daily_orders['Date'].max())

"""Set Date as Index"""

daily_orders.set_index(
    'Date',
    inplace=True
)

daily_orders.head()

"""Check Missing Values"""

daily_orders.isnull().sum()

"""Plot Daily Orders"""

plt.figure(figsize=(15,5))

plt.plot(
    daily_orders['Orders']
)

plt.title(
    'Coffee Shop Daily Orders'
)

plt.xlabel('Date')
plt.ylabel('Orders')

plt.grid(True)

plt.show()

"""| Observation                        | Interpretation                         |
| ---------------------------------- | -------------------------------------- |
| Orders fluctuate between 20 and 55 | Daily demand changes frequently        |
| No strong upward trend             | Orders are relatively stable over time |
| No strong downward trend           | Business demand is not declining       |
| Peaks around 50–55 orders          | High-demand days occurred              |
| Lowest values around 20 orders     | Low-demand days occurred               |
| Average range 30–40 orders         | Typical daily order volume             |

============

| Condition                   | Result        |
| --------------------------- | ------------- |
| Single Variable             | ✅ Orders Only |
| Strong Trend Present?       | ❌ No          |
| Strong Seasonality Present? | ❌ No          |
| Stable Demand Pattern?      | ✅ Yes         |
| Suitable for SES?           | ✅ Yes         |

============

The graph shows random fluctuations around a stable average level without a clear trend or seasonal pattern. Therefore, Simple Exponential Smoothing (SES) is an appropriate forecasting model.

Train-Test Split
"""

train_size = int(
    len(daily_orders)*0.80
)

train = daily_orders.iloc[:train_size]

test = daily_orders.iloc[train_size:]

print("Train :", train.shape)

print("Test :", test.shape)

"""Build SES Model"""

model = SimpleExpSmoothing(
    train['Orders']
)

model

"""| Output             | Meaning                        |
| ------------------ | ------------------------------ |
| SimpleExpSmoothing | SES model selected             |
| train['Orders']    | Daily orders used for training |
| 0x7cace8dbf4d0     | Memory address of model object |
| Error?             | ❌ No                           |
| Model Created?     | ✅ Yes                          |
| Model Trained?     | ❌ Not yet                      |

Train SES Model
"""

model_fit = model.fit(
    optimized=True
)

print(
    model_fit.summary()
)

"""Forecast Test Data"""

forecast = model_fit.forecast(
    len(test)
)

forecast.head()

"""Actual vs Forecast Graph"""

plt.figure(figsize=(15,5))

plt.plot(
    test.index,
    test['Orders'],
    label='Actual Orders'
)

plt.plot(
    test.index,
    forecast,
    label='Forecast Orders'
)

plt.title(
    'Actual vs Forecast'
)

plt.xlabel('Date')

plt.ylabel('Orders')

plt.legend()

plt.grid(True)

plt.show()

"""Why is the Forecast a Straight Line?

SES formula gives more importance to the latest smoothed value.

Since:

Trend = None
Seasonality = None

The model assumes:

Future demand will be approximately equal to the recent average demand.

Therefore:

Forecast Day 1 = 34.5
Forecast Day 2 = 34.5
Forecast Day 3 = 34.5
...

All future values become nearly the same.

===============

**Business Interpretation**

| Result                 | Meaning                       |
| ---------------------- | ----------------------------- |
| Average Orders ≈ 34–35 | Expected daily demand         |
| No Strong Trend        | Business is stable            |
| No Seasonality         | Demand is consistent          |
| Spikes Are Random      | Difficult to predict with SES |

================

Model Strengths

| Strength             | Reason                               |
| -------------------- | ------------------------------------ |
| Simple               | Easy to implement                    |
| Fast                 | Very low computation                 |
| Good for Stable Data | Matches your dataset characteristics |
| Good Baseline Model  | Useful comparison model              |

=================

SES is suitable for short-term forecasting of stable coffee shop demand

Calculate MAE
"""

mae = mean_absolute_error(
    test['Orders'],
    forecast
)

print("MAE :", mae)

"""Calculate RMSE"""

rmse = np.sqrt(
    mean_squared_error(
        test['Orders'],
        forecast
    )
)

print("RMSE :", rmse)

"""Metrics Table"""

metrics_table = pd.DataFrame({
    'Metric':['MAE','RMSE'],
    'Value':[mae,rmse]
})

metrics_table

"""| Metric         | Answer                                                                           |
| -------------- | -------------------------------------------------------------------------------- |
| MAE            | The average forecast error is 5.55 orders per day.                               |
| RMSE           | The root mean square error is 6.91 orders.                                       |
| Interpretation | Forecast errors are relatively small compared to the average daily demand.       |
| Conclusion     | The SES model provides satisfactory short-term forecasts for coffee shop orders. |

Forecast Next 7 Days
"""

future_forecast = model_fit.forecast(
    steps=7
)

future_forecast

"""Create Future Dates"""

future_dates = pd.date_range(
    start=daily_orders.index[-1],
    periods=8,
    freq='D'
)[1:]

"""Create Future Forecast Table"""

future_df = pd.DataFrame({
    'Forecast_Orders':
    future_forecast.values
},
index=future_dates)

future_df

"""| Observation              | Meaning                     |
| ------------------------ | --------------------------- |
| Forecast Orders ≈ 34/day | Expected daily demand       |
| No Increasing Trend      | Orders likely remain stable |
| No Decreasing Trend      | Business is not declining   |
| Stable Forecast          | Consistent customer demand  |

==========

**Forecast Summary Table**

| Metric                  | Result |
| ----------------------- | ------ |
| Forecast Horizon        | 7 Days |
| Average Forecast Orders | 34.38  |
| Trend Detected          | No     |
| Seasonality Detected    | No     |
| Demand Pattern          | Stable |
| Forecast Shape          | Flat   |
| SES Suitability         | High   |

"""